/**
 * Persisting a lease to a git-ignored env file — §5 of
 * docs/Worktree-Port-Leasing.md.
 *
 * The launcher exports the leased ports to its children, but a developer who
 * hand-restarts a single service starts a process the launcher never touched.
 * Without a file on disk that process falls back to the slot-0 defaults and
 * quietly joins the wrong stack.
 */
import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';

/**
 * Marker on line 1. Its absence means a human wrote the file, and
 * {@link writeEnvFile} will not touch it.
 */
export const ENV_FILE_HEADER =
  '# GENERATED by the worktree port lease — do not edit.';

const VALID_ENV_NAME = /^[A-Za-z_][A-Za-z0-9_]*$/;
// Bare values a dotenv parser reads back unchanged; anything else gets quoted.
const BARE_VALUE = /^[A-Za-z0-9_@%+=:,./-]*$/;

export interface RenderEnvFileOptions {
  /** The variables to write, e.g. from `envForSlot` + `resolveUrlTemplates`. */
  env: Record<string, string>;
  slot: number;
  worktreePath?: string | null;
  branch?: string | null;
  header?: string;
  /** Extra comment lines — typically how to regenerate the file. */
  notes?: string[];
}

/** Serializes a lease as a dotenv file body. Pure. */
export function renderEnvFile({
  env,
  slot,
  worktreePath,
  branch,
  header = ENV_FILE_HEADER,
  notes = [],
}: RenderEnvFileOptions): string {
  const lines = [
    header,
    '#',
    `# Worktree port lease — slot ${slot}${
      branch ? ` · branch ${branch}` : ''
    }`,
  ];
  if (worktreePath) lines.push(`# worktree ${worktreePath}`);
  if (notes.length) {
    lines.push('#');
    for (const note of notes) lines.push(`# ${note}`);
  }
  lines.push('');

  for (const [name, value] of Object.entries(env)) {
    if (!VALID_ENV_NAME.test(name)) {
      throw new Error(
        `"${name}" is not a valid environment variable name; refusing to write ` +
          `an env file a shell would misparse.`
      );
    }
    lines.push(`${name}=${quoteIfNeeded(value)}`);
  }

  lines.push('');
  return lines.join('\n');
}

function quoteIfNeeded(value: string): string {
  if (BARE_VALUE.test(value)) return value;
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n');
  return `"${escaped}"`;
}

export type EnvFileAction =
  | 'written'
  | 'removed'
  | 'unchanged'
  | 'skipped-foreign';

export interface WriteEnvFileOptions extends RenderEnvFileOptions {
  /** Absolute path of the env file to manage. */
  filePath: string;
  /**
   * At slot 0, delete the file instead of writing it. Defaults to `true`: the
   * primary worktree's ports are already the historical ones, so writing them
   * again is only a second place for them to drift — and leaving no file keeps
   * the main checkout and CI byte-identical to before the lease existed.
   */
  removeAtSlotZero?: boolean;
}

export interface WriteEnvFileResult {
  action: EnvFileAction;
  filePath: string;
}

/**
 * Writes, removes, or leaves the worktree's env file.
 *
 * Refuses to overwrite a file whose first line is not the header, so a
 * hand-authored file predating the lease is reported rather than clobbered.
 */
export function writeEnvFile(options: WriteEnvFileOptions): WriteEnvFileResult {
  const {
    filePath,
    slot,
    header = ENV_FILE_HEADER,
    removeAtSlotZero = true,
  } = options;

  const existing = existsSync(filePath) ? readFileSync(filePath, 'utf8') : null;

  if (existing !== null && !existing.startsWith(header)) {
    return { action: 'skipped-foreign', filePath };
  }

  if (slot === 0 && removeAtSlotZero) {
    if (existing === null) return { action: 'unchanged', filePath };
    rmSync(filePath, { force: true });
    return { action: 'removed', filePath };
  }

  const next = renderEnvFile(options);
  if (existing === next) return { action: 'unchanged', filePath };

  writeFileSync(filePath, next, 'utf8');
  return { action: 'written', filePath };
}

/** Parses a rendered env file back into variables. Ignores comments and blanks. */
export function parseEnvFile(contents: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of contents.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq <= 0) continue;
    const name = trimmed.slice(0, eq);
    let value = trimmed.slice(eq + 1);
    if (value.startsWith('"') && value.endsWith('"') && value.length > 1) {
      value = value
        .slice(1, -1)
        .replace(/\\n/g, '\n')
        .replace(/\\"/g, '"')
        .replace(/\\\\/g, '\\');
    }
    out[name] = value;
  }
  return out;
}
