import type { Request } from 'express';
import { GoogleAuthEmulateStrategy } from './google-auth-emulate.strategy';
import { GoogleAuthEmulateService } from './google-auth-emulate.service';
import { InMemoryOAuthStateStore } from './google-auth-emulate.state-store';

/**
 * Drives the strategy through passport-oauth2's own `authenticate` flow.
 *
 * The unit-level specs call `authorizationParams`/`validate` directly, which
 * would still pass if passport-oauth2 never handed the request to our state
 * store. These cases pin that wiring: the store must receive the request (arity
 * dispatch), the nonce must reach the authorization URL, and an unknown `state`
 * must fail the callback.
 */
describe('GoogleAuthEmulateStrategy (passport-oauth2 wiring)', () => {
  let strategy: GoogleAuthEmulateStrategy;
  let service: GoogleAuthEmulateService;

  const stateStore = (): InMemoryOAuthStateStore =>
    (
      strategy as unknown as {
        stateStore: InMemoryOAuthStateStore;
      }
    ).stateStore;

  /** Replace a passport framework callback (redirect/fail) with a spy. */
  const stub = (name: 'redirect' | 'fail'): jest.Mock => {
    const fn = jest.fn();
    (strategy as unknown as Record<string, unknown>)[name] = fn;
    return fn;
  };

  beforeEach(() => {
    service = new GoogleAuthEmulateService();
    strategy = new GoogleAuthEmulateStrategy(service);
  });

  it('sends a state and nonce generated by the configured store', () => {
    const redirect = stub('redirect');

    strategy.authenticate({ query: {} } as unknown as Request, {});

    expect(redirect).toHaveBeenCalledTimes(1);
    const url = new URL(redirect.mock.calls[0][0] as string);

    expect(url.searchParams.get('response_type')).toBe('code');
    expect(url.searchParams.get('client_id')).toBe(
      'example-client-id.apps.googleusercontent.com'
    );
    expect(url.searchParams.get('scope')).toBe('openid profile email');

    const state = url.searchParams.get('state');
    const nonce = url.searchParams.get('nonce');
    expect(state).toBeTruthy();
    expect(nonce).toBeTruthy();
    expect(state).not.toBe(nonce);

    // The store persisted the nonce under the generated state handle, which is
    // what lets the callback bind the ID token back to this request.
    expect(stateStore().consume(state as string)).toMatchObject({ nonce });
  });

  it('fails the callback when the state is unknown', () => {
    const fail = stub('fail');
    const redirect = stub('redirect');

    strategy.authenticate(
      {
        query: { code: 'authorization-code', state: 'not-a-known-handle' },
      } as unknown as Request,
      {}
    );

    expect(fail).toHaveBeenCalledWith(
      { message: 'Invalid or expired OAuth state parameter' },
      403
    );
    expect(redirect).not.toHaveBeenCalled();
  });
});
