import { logger, PromiseExecutor } from '@nx/devkit';
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from 'fs';
import { join, relative } from 'path';
import { generateEndpoints } from '@rtk-query/codegen-openapi';
import { GenerateAllClientExecutorSchema } from './schema';

interface BackendProject {
  name: string;
  slug: string;
  openApiPath: string;
}

const BANNER = `// AUTO-GENERATED FILE @generated by @open-kingdom/plugin-openapi
// Run "nx run @open-kingdom/plugin-openapi:generate-client-all" to regenerate.
`;

const runExecutor: PromiseExecutor<GenerateAllClientExecutorSchema> = async (
  options,
  context
) => {
  const workspaceRoot = context.root ?? process.cwd();
  const outputRoot = join(
    workspaceRoot,
    options.outputRoot ?? 'libs/shared/frontend/data-access-api-client/src/lib'
  );

  const backends = findBackends(workspaceRoot);

  if (backends.length === 0) {
    logger.warn(
      'No backends with OpenAPI files were found in data-access-api-client/src/lib/.'
    );
    writeIndex(outputRoot, []);
    return { success: true };
  }

  let hasErrors = false;

  for (const backend of backends) {
    if (!existsSync(backend.openApiPath)) {
      logger.error(
        `Missing OpenAPI file for ${backend.name}: ${backend.openApiPath}`
      );
      hasErrors = true;
      continue;
    }

    // Generate clients in the same directory as openapi.json
    const outputDir = join(outputRoot, backend.slug);
    const outputFile = join(outputDir, 'api.ts');
    const baseApiPath = '../baseApi';

    // Ensure directory exists (don't delete it - openapi.json is in there!)
    mkdirSync(outputDir, { recursive: true });

    logger.info(
      `Generating client for ${backend.name} -> ${relative(
        workspaceRoot,
        outputDir
      )}`
    );

    try {
      await generateEndpoints({
        schemaFile: backend.openApiPath,
        apiFile: baseApiPath,
        apiImport: 'baseApi',
        exportName: 'api',
        outputFile,
        hooks: true,
        tag: true,
      });

      // Read the generated file and fix the import path
      if (existsSync(outputFile)) {
        let content = readFileSync(outputFile, 'utf-8');
        content = content.replace(
          /import\s+{([^}]+)}\s+from\s+["'][^"']*["'];?/,
          `import {$1} from "${baseApiPath}";`
        );
        writeFileSync(outputFile, `${BANNER}${content}`);
      }
    } catch (error) {
      hasErrors = true;
      logger.error(
        `Failed to generate ${backend.name}: ${
          error instanceof Error ? error.message : error
        }`
      );
    }
  }

  writeIndex(
    outputRoot,
    backends.map((b) => ({
      slug: b.slug,
      identifier: slugToIdentifier(b.slug),
    }))
  );

  return { success: !hasErrors };
};

export default runExecutor;

function findBackends(workspaceRoot: string): BackendProject[] {
  const apiClientLibDir = join(
    workspaceRoot,
    'libs/shared/frontend/data-access-api-client/src/lib'
  );

  if (!existsSync(apiClientLibDir)) return [];

  const backends: BackendProject[] = [];

  // Scan the lib directory for backend folders (each folder with openapi.json is a backend)
  for (const dir of readdirSync(apiClientLibDir, { withFileTypes: true })) {
    if (!dir.isDirectory()) continue;

    const backendDir = join(apiClientLibDir, dir.name);
    const openApiPath = join(backendDir, 'openapi.json');

    // Only include directories that have an openapi.json file
    if (!existsSync(openApiPath)) continue;

    backends.push({
      name: dir.name,
      slug: dir.name,
      openApiPath,
    });
  }

  return backends;
}

function slugToIdentifier(slug: string): string {
  const words = slug.split('-').filter(Boolean);
  if (words.length === 0) return 'client';
  return (
    words[0] +
    words
      .slice(1)
      .map((w) => w[0].toUpperCase() + w.slice(1))
      .join('')
  );
}

function writeIndex(
  outputRoot: string,
  entries: Array<{ slug: string; identifier: string }>
) {
  mkdirSync(outputRoot, { recursive: true });
  const exports =
    entries.length === 0
      ? 'export {};'
      : entries
          .map((entry) =>
            [
              `export * from './${entry.slug}/api';`,
              `export * as ${entry.identifier} from './${entry.slug}/api';`,
            ].join('\n')
          )
          .join('\n');
  writeFileSync(join(outputRoot, 'index.ts'), `${BANNER}${exports}\n`);
}
