// AUTO-GENERATED FILE @generated by @open-kingdom/plugin-openapi
// Run "nx run @open-kingdom/plugin-openapi:generate-client-all" to regenerate.
import { baseApi as api } from "../baseApi";
export const addTagTypes = [
  "Authentication",
  "Email",
  "Invitations",
  "Users",
  "GCP Resources",
] as const;
const injectedRtkApi = api
  .enhanceEndpoints({
    addTagTypes,
  })
  .injectEndpoints({
    endpoints: (build) => ({
      authControllerLogin: build.mutation<
        AuthControllerLoginApiResponse,
        AuthControllerLoginApiArg
      >({
        query: (queryArg) => ({
          url: `/api/auth/login`,
          method: "POST",
          body: queryArg.loginDto,
        }),
        invalidatesTags: ["Authentication"],
      }),
      authControllerGetProfile: build.query<
        AuthControllerGetProfileApiResponse,
        AuthControllerGetProfileApiArg
      >({
        query: () => ({ url: `/api/profile` }),
        providesTags: ["Authentication"],
      }),
      emailControllerSendEmail: build.mutation<
        EmailControllerSendEmailApiResponse,
        EmailControllerSendEmailApiArg
      >({
        query: (queryArg) => ({
          url: `/api/email/send`,
          method: "POST",
          body: queryArg.sendEmailDto,
        }),
        invalidatesTags: ["Email"],
      }),
      invitationsControllerInvite: build.mutation<
        InvitationsControllerInviteApiResponse,
        InvitationsControllerInviteApiArg
      >({
        query: (queryArg) => ({
          url: `/api/invitations/invite`,
          method: "POST",
          body: queryArg.inviteUserDto,
        }),
        invalidatesTags: ["Invitations"],
      }),
      invitationsControllerValidate: build.query<
        InvitationsControllerValidateApiResponse,
        InvitationsControllerValidateApiArg
      >({
        query: (queryArg) => ({
          url: `/api/invitations/validate/${queryArg.token}`,
        }),
        providesTags: ["Invitations"],
      }),
      invitationsControllerAccept: build.mutation<
        InvitationsControllerAcceptApiResponse,
        InvitationsControllerAcceptApiArg
      >({
        query: (queryArg) => ({
          url: `/api/invitations/accept`,
          method: "POST",
          body: queryArg.acceptInvitationDto,
        }),
        invalidatesTags: ["Invitations"],
      }),
      usersControllerFindAll: build.query<
        UsersControllerFindAllApiResponse,
        UsersControllerFindAllApiArg
      >({
        query: () => ({ url: `/api/users` }),
        providesTags: ["Users"],
      }),
      usersControllerFindOne: build.query<
        UsersControllerFindOneApiResponse,
        UsersControllerFindOneApiArg
      >({
        query: (queryArg) => ({ url: `/api/users/${queryArg.id}` }),
        providesTags: ["Users"],
      }),
      usersControllerDelete: build.mutation<
        UsersControllerDeleteApiResponse,
        UsersControllerDeleteApiArg
      >({
        query: (queryArg) => ({
          url: `/api/users/${queryArg.id}`,
          method: "DELETE",
        }),
        invalidatesTags: ["Users"],
      }),
      gcpProjectsControllerListProjects: build.query<
        GcpProjectsControllerListProjectsApiResponse,
        GcpProjectsControllerListProjectsApiArg
      >({
        query: (queryArg) => ({
          url: `/api/gcp/projects`,
          params: {
            parent: queryArg.parent,
          },
        }),
        providesTags: ["GCP Resources"],
      }),
      gcpProjectsControllerCreateProject: build.mutation<
        GcpProjectsControllerCreateProjectApiResponse,
        GcpProjectsControllerCreateProjectApiArg
      >({
        query: (queryArg) => ({
          url: `/api/gcp/projects`,
          method: "POST",
          body: queryArg.createProjectDto,
        }),
        invalidatesTags: ["GCP Resources"],
      }),
    }),
    overrideExisting: false,
  });
export { injectedRtkApi as api };
export type AuthControllerLoginApiResponse =
  /** status 200 Login successful */ LoginResponseDto;
export type AuthControllerLoginApiArg = {
  /** User login credentials */
  loginDto: LoginDto;
};
export type AuthControllerGetProfileApiResponse =
  /** status 200 User profile retrieved successfully */ ProfileResponseDto;
export type AuthControllerGetProfileApiArg = void;
export type EmailControllerSendEmailApiResponse =
  /** status 201 Email sent successfully */ SendEmailResponseDto;
export type EmailControllerSendEmailApiArg = {
  /** Email details */
  sendEmailDto: SendEmailDto;
};
export type InvitationsControllerInviteApiResponse = unknown;
export type InvitationsControllerInviteApiArg = {
  inviteUserDto: InviteUserDto;
};
export type InvitationsControllerValidateApiResponse =
  /** status 200 Validation result */ {
    valid?: boolean;
    email?: string | null;
    role?: ("guest" | "user" | "admin") | null;
  };
export type InvitationsControllerValidateApiArg = {
  token: string;
};
export type InvitationsControllerAcceptApiResponse = unknown;
export type InvitationsControllerAcceptApiArg = {
  acceptInvitationDto: AcceptInvitationDto;
};
export type UsersControllerFindAllApiResponse = unknown;
export type UsersControllerFindAllApiArg = void;
export type UsersControllerFindOneApiResponse = unknown;
export type UsersControllerFindOneApiArg = {
  id: number;
};
export type UsersControllerDeleteApiResponse = unknown;
export type UsersControllerDeleteApiArg = {
  id: number;
};
export type GcpProjectsControllerListProjectsApiResponse =
  /** status 200 List of projects */ GcpProjectSummaryDto[];
export type GcpProjectsControllerListProjectsApiArg = {
  /** Parent resource: folders/{folder_id} or organizations/{org_id} */
  parent: string;
};
export type GcpProjectsControllerCreateProjectApiResponse =
  /** status 201 Project created successfully */ CreateProjectResponseDto;
export type GcpProjectsControllerCreateProjectApiArg = {
  /** Project creation details */
  createProjectDto: CreateProjectDto;
};
export type LoginResponseDto = {
  /** JWT access token */
  access_token: string;
};
export type LoginDto = {
  /** User email address */
  email: string;
  /** User password */
  password: string;
};
export type ProfileResponseDto = {
  /** User ID */
  id: number;
  /** User first name */
  firstName: string | null;
  /** User last name */
  lastName: string | null;
  /** User email address */
  email: string;
};
export type SendEmailResponseDto = {
  /** Whether the email was sent successfully */
  success: boolean;
  /** Gmail message ID if successful */
  messageId?: string;
  /** Error message if failed */
  error?: string;
};
export type SendEmailDto = {
  /** Recipient email address */
  to: string;
  /** Email subject line */
  subject: string;
  /** Email body content */
  body: string;
};
export type InviteUserDto = {
  /** Email address of the user to invite */
  email: string;
  /** Role to assign to the invited user */
  role?: "guest" | "user" | "admin";
};
export type AcceptInvitationDto = {
  /** Invitation token from the invite link */
  token: string;
  /** Password for the new account */
  password: string;
  /** First name of the user */
  firstName?: string;
  /** Last name of the user */
  lastName?: string;
};
export type GcpProjectSummaryDto = {
  /** Full resource name (e.g. projects/123) */
  name: string;
  /** Project ID */
  projectId: string;
  /** Display name */
  displayName?: string;
  /** Project lifecycle state (e.g. ACTIVE, DELETE_REQUESTED) */
  state?: object;
};
export type CreateProjectResponseDto = {
  /** Full resource name (e.g. projects/123) */
  name: string;
  /** Project ID */
  projectId: string;
  /** Display name */
  displayName?: string;
  /** Project lifecycle state */
  state?: object;
};
export type CreateProjectDto = {
  /** Project ID (must be unique, lowercase letters, numbers, and hyphens) */
  projectId: string;
  /** Display name for the project */
  displayName?: string;
  /** Parent resource: folders/{folder_id} or organizations/{org_id} */
  parent: string;
};
export const {
  useAuthControllerLoginMutation,
  useAuthControllerGetProfileQuery,
  useEmailControllerSendEmailMutation,
  useInvitationsControllerInviteMutation,
  useInvitationsControllerValidateQuery,
  useInvitationsControllerAcceptMutation,
  useUsersControllerFindAllQuery,
  useUsersControllerFindOneQuery,
  useUsersControllerDeleteMutation,
  useGcpProjectsControllerListProjectsQuery,
  useGcpProjectsControllerCreateProjectMutation,
} = injectedRtkApi;
