// AUTO-GENERATED FILE @generated by @open-kingdom/plugin-openapi
// Run "nx run @open-kingdom/plugin-openapi:generate-client-all" to regenerate.
import { baseApi as api } from "../baseApi";
export const addTagTypes = ["Authentication", "Email"] as const;
const injectedRtkApi = api
  .enhanceEndpoints({
    addTagTypes,
  })
  .injectEndpoints({
    endpoints: (build) => ({
      authControllerLogin: build.mutation<
        AuthControllerLoginApiResponse,
        AuthControllerLoginApiArg
      >({
        query: (queryArg) => ({
          url: `/api/auth/login`,
          method: "POST",
          body: queryArg.loginDto,
        }),
        invalidatesTags: ["Authentication"],
      }),
      authControllerGetProfile: build.query<
        AuthControllerGetProfileApiResponse,
        AuthControllerGetProfileApiArg
      >({
        query: () => ({ url: `/api/profile` }),
        providesTags: ["Authentication"],
      }),
      emailControllerSendEmail: build.mutation<
        EmailControllerSendEmailApiResponse,
        EmailControllerSendEmailApiArg
      >({
        query: (queryArg) => ({
          url: `/api/email/send`,
          method: "POST",
          body: queryArg.sendEmailDto,
        }),
        invalidatesTags: ["Email"],
      }),
    }),
    overrideExisting: false,
  });
export { injectedRtkApi as api };
export type AuthControllerLoginApiResponse =
  /** status 200 Login successful */ LoginResponseDto;
export type AuthControllerLoginApiArg = {
  /** User login credentials */
  loginDto: LoginDto;
};
export type AuthControllerGetProfileApiResponse =
  /** status 200 User profile retrieved successfully */ ProfileResponseDto;
export type AuthControllerGetProfileApiArg = void;
export type EmailControllerSendEmailApiResponse =
  /** status 201 Email sent successfully */ SendEmailResponseDto;
export type EmailControllerSendEmailApiArg = {
  /** Email details */
  sendEmailDto: SendEmailDto;
};
export type LoginResponseDto = {
  /** JWT access token */
  access_token: string;
};
export type LoginDto = {
  /** User email address */
  email: string;
  /** User password */
  password: string;
};
export type ProfileResponseDto = {
  /** User ID */
  id: number;
  /** User first name */
  firstName: string | null;
  /** User last name */
  lastName: string | null;
  /** User email address */
  email: string;
  /** ID of user who invited this user */
  invitee: number | null;
  /** User role */
  role: "guest" | "user" | "admin";
};
export type SendEmailResponseDto = {
  /** Whether the email was sent successfully */
  success: boolean;
  /** Gmail message ID if successful */
  messageId?: string;
  /** Error message if failed */
  error?: string;
};
export type SendEmailDto = {
  /** Recipient email address */
  to: string;
  /** Email subject line */
  subject: string;
  /** Email body content */
  body: string;
};
export const {
  useAuthControllerLoginMutation,
  useAuthControllerGetProfileQuery,
  useEmailControllerSendEmailMutation,
} = injectedRtkApi;
