// AUTO-GENERATED FILE @generated by @open-kingdom/plugin-openapi
// Run "nx run @open-kingdom/plugin-openapi:generate-client-all" to regenerate.
import { baseApi as api } from "../baseApi";
export const addTagTypes = [
  "Authentication",
  "Email",
  "Invitations",
  "Users",
  "Roles",
  "Permissions",
  "User Roles",
  "GCP Resources",
  "GCS Storage",
  "YouTube Search",
  "Lead Conversion",
  "CRM Dashboard",
  "Configurable Lookups",
  "Activity Log",
  "Companies",
  "Contacts",
  "Leads",
  "Opportunities",
  "Twin",
  "YouTube Twin",
  "Google Auth Emulate",
] as const;
const injectedRtkApi = api
  .enhanceEndpoints({
    addTagTypes,
  })
  .injectEndpoints({
    endpoints: (build) => ({
      authControllerLogin: build.mutation<
        AuthControllerLoginApiResponse,
        AuthControllerLoginApiArg
      >({
        query: (queryArg) => ({
          url: `/api/auth/login`,
          method: "POST",
          body: queryArg.loginDto,
        }),
        invalidatesTags: ["Authentication"],
      }),
      authControllerGetProfile: build.query<
        AuthControllerGetProfileApiResponse,
        AuthControllerGetProfileApiArg
      >({
        query: () => ({ url: `/api/profile` }),
        providesTags: ["Authentication"],
      }),
      emailControllerSendEmail: build.mutation<
        EmailControllerSendEmailApiResponse,
        EmailControllerSendEmailApiArg
      >({
        query: (queryArg) => ({
          url: `/api/email/send`,
          method: "POST",
          body: queryArg.sendEmailDto,
        }),
        invalidatesTags: ["Email"],
      }),
      invitationsControllerFindAll: build.query<
        InvitationsControllerFindAllApiResponse,
        InvitationsControllerFindAllApiArg
      >({
        query: () => ({ url: `/api/invitations` }),
        providesTags: ["Invitations"],
      }),
      invitationsControllerInvite: build.mutation<
        InvitationsControllerInviteApiResponse,
        InvitationsControllerInviteApiArg
      >({
        query: (queryArg) => ({
          url: `/api/invitations/invite`,
          method: "POST",
          body: queryArg.inviteUserDto,
        }),
        invalidatesTags: ["Invitations"],
      }),
      invitationsControllerValidate: build.query<
        InvitationsControllerValidateApiResponse,
        InvitationsControllerValidateApiArg
      >({
        query: (queryArg) => ({
          url: `/api/invitations/validate/${queryArg.token}`,
        }),
        providesTags: ["Invitations"],
      }),
      invitationsControllerAccept: build.mutation<
        InvitationsControllerAcceptApiResponse,
        InvitationsControllerAcceptApiArg
      >({
        query: (queryArg) => ({
          url: `/api/invitations/accept`,
          method: "POST",
          body: queryArg.acceptInvitationDto,
        }),
        invalidatesTags: ["Invitations"],
      }),
      invitationsControllerCancel: build.mutation<
        InvitationsControllerCancelApiResponse,
        InvitationsControllerCancelApiArg
      >({
        query: (queryArg) => ({
          url: `/api/invitations/${queryArg.id}`,
          method: "DELETE",
        }),
        invalidatesTags: ["Invitations"],
      }),
      usersControllerFindAll: build.query<
        UsersControllerFindAllApiResponse,
        UsersControllerFindAllApiArg
      >({
        query: () => ({ url: `/api/users` }),
        providesTags: ["Users"],
      }),
      usersControllerFindOne: build.query<
        UsersControllerFindOneApiResponse,
        UsersControllerFindOneApiArg
      >({
        query: (queryArg) => ({ url: `/api/users/${queryArg.id}` }),
        providesTags: ["Users"],
      }),
      usersControllerDelete: build.mutation<
        UsersControllerDeleteApiResponse,
        UsersControllerDeleteApiArg
      >({
        query: (queryArg) => ({
          url: `/api/users/${queryArg.id}`,
          method: "DELETE",
        }),
        invalidatesTags: ["Users"],
      }),
      rolesControllerFindAll: build.query<
        RolesControllerFindAllApiResponse,
        RolesControllerFindAllApiArg
      >({
        query: () => ({ url: `/api/roles` }),
        providesTags: ["Roles"],
      }),
      rolesControllerCreate: build.mutation<
        RolesControllerCreateApiResponse,
        RolesControllerCreateApiArg
      >({
        query: (queryArg) => ({
          url: `/api/roles`,
          method: "POST",
          body: queryArg.createRoleDto,
        }),
        invalidatesTags: ["Roles"],
      }),
      rolesControllerFindOne: build.query<
        RolesControllerFindOneApiResponse,
        RolesControllerFindOneApiArg
      >({
        query: (queryArg) => ({ url: `/api/roles/${queryArg.id}` }),
        providesTags: ["Roles"],
      }),
      rolesControllerUpdate: build.mutation<
        RolesControllerUpdateApiResponse,
        RolesControllerUpdateApiArg
      >({
        query: (queryArg) => ({
          url: `/api/roles/${queryArg.id}`,
          method: "PATCH",
          body: queryArg.updateRoleDto,
        }),
        invalidatesTags: ["Roles"],
      }),
      rolesControllerDelete: build.mutation<
        RolesControllerDeleteApiResponse,
        RolesControllerDeleteApiArg
      >({
        query: (queryArg) => ({
          url: `/api/roles/${queryArg.id}`,
          method: "DELETE",
        }),
        invalidatesTags: ["Roles"],
      }),
      rolesControllerGetPermissions: build.query<
        RolesControllerGetPermissionsApiResponse,
        RolesControllerGetPermissionsApiArg
      >({
        query: (queryArg) => ({ url: `/api/roles/${queryArg.id}/permissions` }),
        providesTags: ["Roles"],
      }),
      rolesControllerSetPermissions: build.mutation<
        RolesControllerSetPermissionsApiResponse,
        RolesControllerSetPermissionsApiArg
      >({
        query: (queryArg) => ({
          url: `/api/roles/${queryArg.id}/permissions`,
          method: "PUT",
          body: queryArg.setRolePermissionsDto,
        }),
        invalidatesTags: ["Roles"],
      }),
      permissionsControllerFindAll: build.query<
        PermissionsControllerFindAllApiResponse,
        PermissionsControllerFindAllApiArg
      >({
        query: () => ({ url: `/api/permissions` }),
        providesTags: ["Permissions"],
      }),
      permissionsControllerCreate: build.mutation<
        PermissionsControllerCreateApiResponse,
        PermissionsControllerCreateApiArg
      >({
        query: (queryArg) => ({
          url: `/api/permissions`,
          method: "POST",
          body: queryArg.createPermissionDto,
        }),
        invalidatesTags: ["Permissions"],
      }),
      permissionsControllerFindOne: build.query<
        PermissionsControllerFindOneApiResponse,
        PermissionsControllerFindOneApiArg
      >({
        query: (queryArg) => ({ url: `/api/permissions/${queryArg.id}` }),
        providesTags: ["Permissions"],
      }),
      permissionsControllerDelete: build.mutation<
        PermissionsControllerDeleteApiResponse,
        PermissionsControllerDeleteApiArg
      >({
        query: (queryArg) => ({
          url: `/api/permissions/${queryArg.id}`,
          method: "DELETE",
        }),
        invalidatesTags: ["Permissions"],
      }),
      userRolesControllerFindByUser: build.query<
        UserRolesControllerFindByUserApiResponse,
        UserRolesControllerFindByUserApiArg
      >({
        query: (queryArg) => ({ url: `/api/users/${queryArg.userId}/roles` }),
        providesTags: ["User Roles"],
      }),
      userRolesControllerSetRoles: build.mutation<
        UserRolesControllerSetRolesApiResponse,
        UserRolesControllerSetRolesApiArg
      >({
        query: (queryArg) => ({
          url: `/api/users/${queryArg.userId}/roles`,
          method: "PUT",
          body: queryArg.updateUserRolesDto,
        }),
        invalidatesTags: ["User Roles"],
      }),
      userRolesControllerAssignRole: build.mutation<
        UserRolesControllerAssignRoleApiResponse,
        UserRolesControllerAssignRoleApiArg
      >({
        query: (queryArg) => ({
          url: `/api/users/${queryArg.userId}/roles`,
          method: "POST",
          body: queryArg.assignUserRoleDto,
        }),
        invalidatesTags: ["User Roles"],
      }),
      userRolesControllerRemoveRole: build.mutation<
        UserRolesControllerRemoveRoleApiResponse,
        UserRolesControllerRemoveRoleApiArg
      >({
        query: (queryArg) => ({
          url: `/api/users/${queryArg.userId}/roles/${queryArg.roleId}`,
          method: "DELETE",
        }),
        invalidatesTags: ["User Roles"],
      }),
      gcpProjectsControllerListProjects: build.query<
        GcpProjectsControllerListProjectsApiResponse,
        GcpProjectsControllerListProjectsApiArg
      >({
        query: (queryArg) => ({
          url: `/api/gcp/projects`,
          params: {
            parent: queryArg.parent,
          },
        }),
        providesTags: ["GCP Resources"],
      }),
      gcpProjectsControllerCreateProject: build.mutation<
        GcpProjectsControllerCreateProjectApiResponse,
        GcpProjectsControllerCreateProjectApiArg
      >({
        query: (queryArg) => ({
          url: `/api/gcp/projects`,
          method: "POST",
          body: queryArg.createProjectDto,
        }),
        invalidatesTags: ["GCP Resources"],
      }),
      gcsStorageControllerUploadFile: build.mutation<
        GcsStorageControllerUploadFileApiResponse,
        GcsStorageControllerUploadFileApiArg
      >({
        query: (queryArg) => ({
          url: `/api/gcs/upload`,
          method: "POST",
          body: queryArg.uploadFileDto,
        }),
        invalidatesTags: ["GCS Storage"],
      }),
      gcsStorageControllerListFiles: build.query<
        GcsStorageControllerListFilesApiResponse,
        GcsStorageControllerListFilesApiArg
      >({
        query: (queryArg) => ({
          url: `/api/gcs/files`,
          params: {
            bucket: queryArg.bucket,
            prefix: queryArg.prefix,
          },
        }),
        providesTags: ["GCS Storage"],
      }),
      gcsStorageControllerGenerateDownloadUrl: build.query<
        GcsStorageControllerGenerateDownloadUrlApiResponse,
        GcsStorageControllerGenerateDownloadUrlApiArg
      >({
        query: (queryArg) => ({
          url: `/api/gcs/files/${queryArg.bucket}/${queryArg.fileName}/url`,
        }),
        providesTags: ["GCS Storage"],
      }),
      gcsStorageControllerDownloadFile: build.query<
        GcsStorageControllerDownloadFileApiResponse,
        GcsStorageControllerDownloadFileApiArg
      >({
        query: (queryArg) => ({
          url: `/api/gcs/files/${queryArg.bucket}/${queryArg.fileName}/download`,
        }),
        providesTags: ["GCS Storage"],
      }),
      gcsStorageControllerDeleteFile: build.mutation<
        GcsStorageControllerDeleteFileApiResponse,
        GcsStorageControllerDeleteFileApiArg
      >({
        query: (queryArg) => ({
          url: `/api/gcs/files/${queryArg.bucket}/${queryArg.fileName}/delete`,
          method: "POST",
        }),
        invalidatesTags: ["GCS Storage"],
      }),
      gcsStorageControllerActivateErrorMode: build.mutation<
        GcsStorageControllerActivateErrorModeApiResponse,
        GcsStorageControllerActivateErrorModeApiArg
      >({
        query: (queryArg) => ({
          url: `/api/gcs/error-mode`,
          method: "POST",
          body: queryArg.activateErrorModeDto,
        }),
        invalidatesTags: ["GCS Storage"],
      }),
      gcsStorageControllerDeactivateErrorMode: build.mutation<
        GcsStorageControllerDeactivateErrorModeApiResponse,
        GcsStorageControllerDeactivateErrorModeApiArg
      >({
        query: () => ({ url: `/api/gcs/error-mode`, method: "DELETE" }),
        invalidatesTags: ["GCS Storage"],
      }),
      youtubeSearchControllerSearch: build.query<
        YoutubeSearchControllerSearchApiResponse,
        YoutubeSearchControllerSearchApiArg
      >({
        query: (queryArg) => ({
          url: `/api/youtube/search`,
          params: {
            q: queryArg.q,
            maxResults: queryArg.maxResults,
          },
        }),
        providesTags: ["YouTube Search"],
      }),
      youtubeSearchControllerActivateErrorMode: build.mutation<
        YoutubeSearchControllerActivateErrorModeApiResponse,
        YoutubeSearchControllerActivateErrorModeApiArg
      >({
        query: (queryArg) => ({
          url: `/api/youtube/error-mode`,
          method: "POST",
          body: queryArg.youtubeActivateErrorModeDto,
        }),
        invalidatesTags: ["YouTube Search"],
      }),
      youtubeSearchControllerDeactivateErrorMode: build.mutation<
        YoutubeSearchControllerDeactivateErrorModeApiResponse,
        YoutubeSearchControllerDeactivateErrorModeApiArg
      >({
        query: () => ({ url: `/api/youtube/error-mode`, method: "DELETE" }),
        invalidatesTags: ["YouTube Search"],
      }),
      leadConversionControllerConvert: build.mutation<
        LeadConversionControllerConvertApiResponse,
        LeadConversionControllerConvertApiArg
      >({
        query: (queryArg) => ({
          url: `/api/leads/${queryArg.id}/convert`,
          method: "POST",
          body: queryArg.convertLeadRequestDto,
        }),
        invalidatesTags: ["Lead Conversion"],
      }),
      dashboardControllerSnapshot: build.query<
        DashboardControllerSnapshotApiResponse,
        DashboardControllerSnapshotApiArg
      >({
        query: () => ({ url: `/api/crm/dashboard` }),
        providesTags: ["CRM Dashboard"],
      }),
      configurableLookupsControllerFindAll: build.query<
        ConfigurableLookupsControllerFindAllApiResponse,
        ConfigurableLookupsControllerFindAllApiArg
      >({
        query: (queryArg) => ({
          url: `/api/configurable-lookups`,
          params: {
            listKey: queryArg.listKey,
            includeInactive: queryArg.includeInactive,
          },
        }),
        providesTags: ["Configurable Lookups"],
      }),
      configurableLookupsControllerCreate: build.mutation<
        ConfigurableLookupsControllerCreateApiResponse,
        ConfigurableLookupsControllerCreateApiArg
      >({
        query: (queryArg) => ({
          url: `/api/configurable-lookups`,
          method: "POST",
          body: queryArg.createConfigurableLookupDto,
        }),
        invalidatesTags: ["Configurable Lookups"],
      }),
      configurableLookupsControllerFindOne: build.query<
        ConfigurableLookupsControllerFindOneApiResponse,
        ConfigurableLookupsControllerFindOneApiArg
      >({
        query: (queryArg) => ({
          url: `/api/configurable-lookups/${queryArg.id}`,
        }),
        providesTags: ["Configurable Lookups"],
      }),
      configurableLookupsControllerUpdate: build.mutation<
        ConfigurableLookupsControllerUpdateApiResponse,
        ConfigurableLookupsControllerUpdateApiArg
      >({
        query: (queryArg) => ({
          url: `/api/configurable-lookups/${queryArg.id}`,
          method: "PATCH",
          body: queryArg.updateConfigurableLookupDto,
        }),
        invalidatesTags: ["Configurable Lookups"],
      }),
      configurableLookupsControllerDelete: build.mutation<
        ConfigurableLookupsControllerDeleteApiResponse,
        ConfigurableLookupsControllerDeleteApiArg
      >({
        query: (queryArg) => ({
          url: `/api/configurable-lookups/${queryArg.id}`,
          method: "DELETE",
        }),
        invalidatesTags: ["Configurable Lookups"],
      }),
      activityLogControllerFindAll: build.query<
        ActivityLogControllerFindAllApiResponse,
        ActivityLogControllerFindAllApiArg
      >({
        query: (queryArg) => ({
          url: `/api/activities`,
          params: {
            relatedType: queryArg.relatedType,
            relatedId: queryArg.relatedId,
            scope: queryArg.scope,
          },
        }),
        providesTags: ["Activity Log"],
      }),
      activityLogControllerCreate: build.mutation<
        ActivityLogControllerCreateApiResponse,
        ActivityLogControllerCreateApiArg
      >({
        query: (queryArg) => ({
          url: `/api/activities`,
          method: "POST",
          body: queryArg.createActivityLogEntryDto,
        }),
        invalidatesTags: ["Activity Log"],
      }),
      activityLogControllerFindOne: build.query<
        ActivityLogControllerFindOneApiResponse,
        ActivityLogControllerFindOneApiArg
      >({
        query: (queryArg) => ({ url: `/api/activities/${queryArg.id}` }),
        providesTags: ["Activity Log"],
      }),
      activityLogControllerUpdate: build.mutation<
        ActivityLogControllerUpdateApiResponse,
        ActivityLogControllerUpdateApiArg
      >({
        query: (queryArg) => ({
          url: `/api/activities/${queryArg.id}`,
          method: "PATCH",
          body: queryArg.updateActivityLogEntryDto,
        }),
        invalidatesTags: ["Activity Log"],
      }),
      activityLogControllerDelete: build.mutation<
        ActivityLogControllerDeleteApiResponse,
        ActivityLogControllerDeleteApiArg
      >({
        query: (queryArg) => ({
          url: `/api/activities/${queryArg.id}`,
          method: "DELETE",
        }),
        invalidatesTags: ["Activity Log"],
      }),
      activityLogControllerComplete: build.mutation<
        ActivityLogControllerCompleteApiResponse,
        ActivityLogControllerCompleteApiArg
      >({
        query: (queryArg) => ({
          url: `/api/activities/${queryArg.id}/complete`,
          method: "POST",
          body: queryArg.completeActivityLogEntryDto,
        }),
        invalidatesTags: ["Activity Log"],
      }),
      companiesControllerFindAll: build.query<
        CompaniesControllerFindAllApiResponse,
        CompaniesControllerFindAllApiArg
      >({
        query: (queryArg) => ({
          url: `/api/companies`,
          params: {
            ownerId: queryArg.ownerId,
            status: queryArg.status,
            search: queryArg.search,
            includeArchived: queryArg.includeArchived,
          },
        }),
        providesTags: ["Companies"],
      }),
      companiesControllerCreate: build.mutation<
        CompaniesControllerCreateApiResponse,
        CompaniesControllerCreateApiArg
      >({
        query: (queryArg) => ({
          url: `/api/companies`,
          method: "POST",
          body: queryArg.createCompanyDto,
        }),
        invalidatesTags: ["Companies"],
      }),
      companiesControllerFindOne: build.query<
        CompaniesControllerFindOneApiResponse,
        CompaniesControllerFindOneApiArg
      >({
        query: (queryArg) => ({ url: `/api/companies/${queryArg.id}` }),
        providesTags: ["Companies"],
      }),
      companiesControllerUpdate: build.mutation<
        CompaniesControllerUpdateApiResponse,
        CompaniesControllerUpdateApiArg
      >({
        query: (queryArg) => ({
          url: `/api/companies/${queryArg.id}`,
          method: "PATCH",
          body: queryArg.updateCompanyDto,
        }),
        invalidatesTags: ["Companies"],
      }),
      companiesControllerArchive: build.mutation<
        CompaniesControllerArchiveApiResponse,
        CompaniesControllerArchiveApiArg
      >({
        query: (queryArg) => ({
          url: `/api/companies/${queryArg.id}/archive`,
          method: "POST",
        }),
        invalidatesTags: ["Companies"],
      }),
      companiesControllerRestore: build.mutation<
        CompaniesControllerRestoreApiResponse,
        CompaniesControllerRestoreApiArg
      >({
        query: (queryArg) => ({
          url: `/api/companies/${queryArg.id}/restore`,
          method: "POST",
        }),
        invalidatesTags: ["Companies"],
      }),
      contactsControllerFindAll: build.query<
        ContactsControllerFindAllApiResponse,
        ContactsControllerFindAllApiArg
      >({
        query: (queryArg) => ({
          url: `/api/contacts`,
          params: {
            ownerId: queryArg.ownerId,
            companyId: queryArg.companyId,
            status: queryArg.status,
            search: queryArg.search,
            includeArchived: queryArg.includeArchived,
          },
        }),
        providesTags: ["Contacts"],
      }),
      contactsControllerCreate: build.mutation<
        ContactsControllerCreateApiResponse,
        ContactsControllerCreateApiArg
      >({
        query: (queryArg) => ({
          url: `/api/contacts`,
          method: "POST",
          body: queryArg.createContactDto,
        }),
        invalidatesTags: ["Contacts"],
      }),
      contactsControllerFindOne: build.query<
        ContactsControllerFindOneApiResponse,
        ContactsControllerFindOneApiArg
      >({
        query: (queryArg) => ({ url: `/api/contacts/${queryArg.id}` }),
        providesTags: ["Contacts"],
      }),
      contactsControllerUpdate: build.mutation<
        ContactsControllerUpdateApiResponse,
        ContactsControllerUpdateApiArg
      >({
        query: (queryArg) => ({
          url: `/api/contacts/${queryArg.id}`,
          method: "PATCH",
          body: queryArg.updateContactDto,
        }),
        invalidatesTags: ["Contacts"],
      }),
      contactsControllerArchive: build.mutation<
        ContactsControllerArchiveApiResponse,
        ContactsControllerArchiveApiArg
      >({
        query: (queryArg) => ({
          url: `/api/contacts/${queryArg.id}/archive`,
          method: "POST",
        }),
        invalidatesTags: ["Contacts"],
      }),
      contactsControllerRestore: build.mutation<
        ContactsControllerRestoreApiResponse,
        ContactsControllerRestoreApiArg
      >({
        query: (queryArg) => ({
          url: `/api/contacts/${queryArg.id}/restore`,
          method: "POST",
        }),
        invalidatesTags: ["Contacts"],
      }),
      leadsControllerFindAll: build.query<
        LeadsControllerFindAllApiResponse,
        LeadsControllerFindAllApiArg
      >({
        query: (queryArg) => ({
          url: `/api/leads`,
          params: {
            ownerId: queryArg.ownerId,
            status: queryArg.status,
            search: queryArg.search,
          },
        }),
        providesTags: ["Leads"],
      }),
      leadsControllerCreate: build.mutation<
        LeadsControllerCreateApiResponse,
        LeadsControllerCreateApiArg
      >({
        query: (queryArg) => ({
          url: `/api/leads`,
          method: "POST",
          body: queryArg.createLeadDto,
        }),
        invalidatesTags: ["Leads"],
      }),
      leadsControllerFindOne: build.query<
        LeadsControllerFindOneApiResponse,
        LeadsControllerFindOneApiArg
      >({
        query: (queryArg) => ({ url: `/api/leads/${queryArg.id}` }),
        providesTags: ["Leads"],
      }),
      leadsControllerUpdate: build.mutation<
        LeadsControllerUpdateApiResponse,
        LeadsControllerUpdateApiArg
      >({
        query: (queryArg) => ({
          url: `/api/leads/${queryArg.id}`,
          method: "PATCH",
          body: queryArg.updateLeadDto,
        }),
        invalidatesTags: ["Leads"],
      }),
      leadsControllerDelete: build.mutation<
        LeadsControllerDeleteApiResponse,
        LeadsControllerDeleteApiArg
      >({
        query: (queryArg) => ({
          url: `/api/leads/${queryArg.id}`,
          method: "DELETE",
        }),
        invalidatesTags: ["Leads"],
      }),
      opportunitiesControllerFindAll: build.query<
        OpportunitiesControllerFindAllApiResponse,
        OpportunitiesControllerFindAllApiArg
      >({
        query: (queryArg) => ({
          url: `/api/opportunities`,
          params: {
            ownerId: queryArg.ownerId,
            companyId: queryArg.companyId,
            stage: queryArg.stage,
            search: queryArg.search,
            openOnly: queryArg.openOnly,
          },
        }),
        providesTags: ["Opportunities"],
      }),
      opportunitiesControllerCreate: build.mutation<
        OpportunitiesControllerCreateApiResponse,
        OpportunitiesControllerCreateApiArg
      >({
        query: (queryArg) => ({
          url: `/api/opportunities`,
          method: "POST",
          body: queryArg.createOpportunityDto,
        }),
        invalidatesTags: ["Opportunities"],
      }),
      opportunitiesControllerPipelineSummary: build.query<
        OpportunitiesControllerPipelineSummaryApiResponse,
        OpportunitiesControllerPipelineSummaryApiArg
      >({
        query: (queryArg) => ({
          url: `/api/opportunities/pipeline-summary`,
          params: {
            ownerId: queryArg.ownerId,
          },
        }),
        providesTags: ["Opportunities"],
      }),
      opportunitiesControllerFindOne: build.query<
        OpportunitiesControllerFindOneApiResponse,
        OpportunitiesControllerFindOneApiArg
      >({
        query: (queryArg) => ({ url: `/api/opportunities/${queryArg.id}` }),
        providesTags: ["Opportunities"],
      }),
      opportunitiesControllerUpdate: build.mutation<
        OpportunitiesControllerUpdateApiResponse,
        OpportunitiesControllerUpdateApiArg
      >({
        query: (queryArg) => ({
          url: `/api/opportunities/${queryArg.id}`,
          method: "PATCH",
          body: queryArg.updateOpportunityDto,
        }),
        invalidatesTags: ["Opportunities"],
      }),
      opportunitiesControllerClose: build.mutation<
        OpportunitiesControllerCloseApiResponse,
        OpportunitiesControllerCloseApiArg
      >({
        query: (queryArg) => ({
          url: `/api/opportunities/${queryArg.id}/close`,
          method: "POST",
          body: queryArg.closeOpportunityDto,
        }),
        invalidatesTags: ["Opportunities"],
      }),
      twinControllerGetStatus: build.query<
        TwinControllerGetStatusApiResponse,
        TwinControllerGetStatusApiArg
      >({
        query: () => ({ url: `/api/twin/status` }),
        providesTags: ["Twin"],
      }),
      twinControllerStart: build.mutation<
        TwinControllerStartApiResponse,
        TwinControllerStartApiArg
      >({
        query: () => ({ url: `/api/twin/start`, method: "POST" }),
        invalidatesTags: ["Twin"],
      }),
      twinControllerStop: build.mutation<
        TwinControllerStopApiResponse,
        TwinControllerStopApiArg
      >({
        query: () => ({ url: `/api/twin/stop`, method: "POST" }),
        invalidatesTags: ["Twin"],
      }),
      twinControllerGetGmailEmails: build.query<
        TwinControllerGetGmailEmailsApiResponse,
        TwinControllerGetGmailEmailsApiArg
      >({
        query: () => ({ url: `/api/twin/gmail/emails` }),
        providesTags: ["Twin"],
      }),
      twinControllerResetGmail: build.mutation<
        TwinControllerResetGmailApiResponse,
        TwinControllerResetGmailApiArg
      >({
        query: () => ({ url: `/api/twin/gmail/reset`, method: "POST" }),
        invalidatesTags: ["Twin"],
      }),
      twinControllerSetGmailErrorMode: build.mutation<
        TwinControllerSetGmailErrorModeApiResponse,
        TwinControllerSetGmailErrorModeApiArg
      >({
        query: (queryArg) => ({
          url: `/api/twin/gmail/error-mode`,
          method: "POST",
          body: queryArg.setGmailErrorModeDto,
        }),
        invalidatesTags: ["Twin"],
      }),
      youTubeTwinControllerGetStatus: build.query<
        YouTubeTwinControllerGetStatusApiResponse,
        YouTubeTwinControllerGetStatusApiArg
      >({
        query: () => ({ url: `/api/youtube-twin/status` }),
        providesTags: ["YouTube Twin"],
      }),
      youTubeTwinControllerStart: build.mutation<
        YouTubeTwinControllerStartApiResponse,
        YouTubeTwinControllerStartApiArg
      >({
        query: () => ({ url: `/api/youtube-twin/start`, method: "POST" }),
        invalidatesTags: ["YouTube Twin"],
      }),
      youTubeTwinControllerStop: build.mutation<
        YouTubeTwinControllerStopApiResponse,
        YouTubeTwinControllerStopApiArg
      >({
        query: () => ({ url: `/api/youtube-twin/stop`, method: "POST" }),
        invalidatesTags: ["YouTube Twin"],
      }),
      youTubeTwinControllerReset: build.mutation<
        YouTubeTwinControllerResetApiResponse,
        YouTubeTwinControllerResetApiArg
      >({
        query: () => ({ url: `/api/youtube-twin/reset`, method: "POST" }),
        invalidatesTags: ["YouTube Twin"],
      }),
      googleAuthEmulateControllerGetStatus: build.query<
        GoogleAuthEmulateControllerGetStatusApiResponse,
        GoogleAuthEmulateControllerGetStatusApiArg
      >({
        query: () => ({ url: `/api/google-auth-emulate/status` }),
        providesTags: ["Google Auth Emulate"],
      }),
      googleAuthEmulateControllerStart: build.mutation<
        GoogleAuthEmulateControllerStartApiResponse,
        GoogleAuthEmulateControllerStartApiArg
      >({
        query: () => ({
          url: `/api/google-auth-emulate/start`,
          method: "POST",
        }),
        invalidatesTags: ["Google Auth Emulate"],
      }),
      googleAuthEmulateControllerStop: build.mutation<
        GoogleAuthEmulateControllerStopApiResponse,
        GoogleAuthEmulateControllerStopApiArg
      >({
        query: () => ({ url: `/api/google-auth-emulate/stop`, method: "POST" }),
        invalidatesTags: ["Google Auth Emulate"],
      }),
      googleAuthEmulateControllerReset: build.mutation<
        GoogleAuthEmulateControllerResetApiResponse,
        GoogleAuthEmulateControllerResetApiArg
      >({
        query: () => ({
          url: `/api/google-auth-emulate/reset`,
          method: "POST",
        }),
        invalidatesTags: ["Google Auth Emulate"],
      }),
      googleAuthEmulateControllerGetLoginUrl: build.query<
        GoogleAuthEmulateControllerGetLoginUrlApiResponse,
        GoogleAuthEmulateControllerGetLoginUrlApiArg
      >({
        query: () => ({ url: `/api/google-auth-emulate/login-url` }),
        providesTags: ["Google Auth Emulate"],
      }),
      googleAuthEmulateControllerLogin: build.query<
        GoogleAuthEmulateControllerLoginApiResponse,
        GoogleAuthEmulateControllerLoginApiArg
      >({
        query: () => ({ url: `/api/google-auth-emulate/login` }),
        providesTags: ["Google Auth Emulate"],
      }),
      googleAuthEmulateControllerCallback: build.query<
        GoogleAuthEmulateControllerCallbackApiResponse,
        GoogleAuthEmulateControllerCallbackApiArg
      >({
        query: () => ({ url: `/api/google-auth-emulate/callback` }),
        providesTags: ["Google Auth Emulate"],
      }),
      googleAuthEmulateControllerGetLastResult: build.query<
        GoogleAuthEmulateControllerGetLastResultApiResponse,
        GoogleAuthEmulateControllerGetLastResultApiArg
      >({
        query: () => ({ url: `/api/google-auth-emulate/last-result` }),
        providesTags: ["Google Auth Emulate"],
      }),
      googleAuthEmulateControllerGetLogs: build.query<
        GoogleAuthEmulateControllerGetLogsApiResponse,
        GoogleAuthEmulateControllerGetLogsApiArg
      >({
        query: () => ({ url: `/api/google-auth-emulate/logs` }),
        providesTags: ["Google Auth Emulate"],
      }),
      googleAuthEmulateControllerLogout: build.mutation<
        GoogleAuthEmulateControllerLogoutApiResponse,
        GoogleAuthEmulateControllerLogoutApiArg
      >({
        query: () => ({
          url: `/api/google-auth-emulate/logout`,
          method: "POST",
        }),
        invalidatesTags: ["Google Auth Emulate"],
      }),
    }),
    overrideExisting: false,
  });
export { injectedRtkApi as api };
export type AuthControllerLoginApiResponse =
  /** status 200 Login successful */ LoginResponseDto;
export type AuthControllerLoginApiArg = {
  /** User login credentials */
  loginDto: LoginDto;
};
export type AuthControllerGetProfileApiResponse =
  /** status 200 User profile retrieved successfully */ ProfileResponseDto;
export type AuthControllerGetProfileApiArg = void;
export type EmailControllerSendEmailApiResponse =
  /** status 201 Email sent successfully */ SendEmailResponseDto;
export type EmailControllerSendEmailApiArg = {
  /** Email details */
  sendEmailDto: SendEmailDto;
};
export type InvitationsControllerFindAllApiResponse = unknown;
export type InvitationsControllerFindAllApiArg = void;
export type InvitationsControllerInviteApiResponse = unknown;
export type InvitationsControllerInviteApiArg = {
  inviteUserDto: InviteUserDto;
};
export type InvitationsControllerValidateApiResponse =
  /** status 200 Validation result */ {
    valid?: boolean;
    email?: string | null;
    roleId?: number | null;
  };
export type InvitationsControllerValidateApiArg = {
  token: string;
};
export type InvitationsControllerAcceptApiResponse = unknown;
export type InvitationsControllerAcceptApiArg = {
  acceptInvitationDto: AcceptInvitationDto;
};
export type InvitationsControllerCancelApiResponse = unknown;
export type InvitationsControllerCancelApiArg = {
  id: number;
};
export type UsersControllerFindAllApiResponse = unknown;
export type UsersControllerFindAllApiArg = void;
export type UsersControllerFindOneApiResponse = unknown;
export type UsersControllerFindOneApiArg = {
  id: number;
};
export type UsersControllerDeleteApiResponse = unknown;
export type UsersControllerDeleteApiArg = {
  id: number;
};
export type RolesControllerFindAllApiResponse = unknown;
export type RolesControllerFindAllApiArg = void;
export type RolesControllerCreateApiResponse = unknown;
export type RolesControllerCreateApiArg = {
  createRoleDto: CreateRoleDto;
};
export type RolesControllerFindOneApiResponse = unknown;
export type RolesControllerFindOneApiArg = {
  id: number;
};
export type RolesControllerUpdateApiResponse = unknown;
export type RolesControllerUpdateApiArg = {
  id: number;
  updateRoleDto: UpdateRoleDto;
};
export type RolesControllerDeleteApiResponse = unknown;
export type RolesControllerDeleteApiArg = {
  id: number;
};
export type RolesControllerGetPermissionsApiResponse = unknown;
export type RolesControllerGetPermissionsApiArg = {
  id: number;
};
export type RolesControllerSetPermissionsApiResponse = unknown;
export type RolesControllerSetPermissionsApiArg = {
  id: number;
  setRolePermissionsDto: SetRolePermissionsDto;
};
export type PermissionsControllerFindAllApiResponse = unknown;
export type PermissionsControllerFindAllApiArg = void;
export type PermissionsControllerCreateApiResponse = unknown;
export type PermissionsControllerCreateApiArg = {
  createPermissionDto: CreatePermissionDto;
};
export type PermissionsControllerFindOneApiResponse = unknown;
export type PermissionsControllerFindOneApiArg = {
  id: number;
};
export type PermissionsControllerDeleteApiResponse = unknown;
export type PermissionsControllerDeleteApiArg = {
  id: number;
};
export type UserRolesControllerFindByUserApiResponse = unknown;
export type UserRolesControllerFindByUserApiArg = {
  userId: number;
};
export type UserRolesControllerSetRolesApiResponse = unknown;
export type UserRolesControllerSetRolesApiArg = {
  userId: number;
  updateUserRolesDto: UpdateUserRolesDto;
};
export type UserRolesControllerAssignRoleApiResponse = unknown;
export type UserRolesControllerAssignRoleApiArg = {
  userId: number;
  assignUserRoleDto: AssignUserRoleDto;
};
export type UserRolesControllerRemoveRoleApiResponse = unknown;
export type UserRolesControllerRemoveRoleApiArg = {
  userId: number;
  roleId: number;
};
export type GcpProjectsControllerListProjectsApiResponse =
  /** status 200 List of projects */ GcpProjectSummaryDto[];
export type GcpProjectsControllerListProjectsApiArg = {
  /** Parent resource: folders/{folder_id} or organizations/{org_id} */
  parent: string;
};
export type GcpProjectsControllerCreateProjectApiResponse =
  /** status 201 Project created successfully */ CreateProjectResponseDto;
export type GcpProjectsControllerCreateProjectApiArg = {
  /** Project creation details */
  createProjectDto: CreateProjectDto;
};
export type GcsStorageControllerUploadFileApiResponse =
  /** status 201 File uploaded successfully */ FileMetadataDto;
export type GcsStorageControllerUploadFileApiArg = {
  /** File upload details */
  uploadFileDto: UploadFileDto;
};
export type GcsStorageControllerListFilesApiResponse =
  /** status 200 List of files */ ListFilesResponseDto;
export type GcsStorageControllerListFilesApiArg = {
  /** Bucket name */
  bucket: string;
  /** Prefix filter */
  prefix?: string;
};
export type GcsStorageControllerGenerateDownloadUrlApiResponse =
  /** status 200 Download URL generated successfully */ GetDownloadUrlResponseDto;
export type GcsStorageControllerGenerateDownloadUrlApiArg = {
  /** Bucket name */
  bucket: string;
  /** File name */
  fileName: string;
};
export type GcsStorageControllerDownloadFileApiResponse =
  /** status 200 File content */ {
    /** Base64 encoded file content */
    content?: string;
    metadata?: FileMetadataDto;
  };
export type GcsStorageControllerDownloadFileApiArg = {
  /** Bucket name */
  bucket: string;
  /** File name */
  fileName: string;
};
export type GcsStorageControllerDeleteFileApiResponse = unknown;
export type GcsStorageControllerDeleteFileApiArg = {
  /** Bucket name */
  bucket: string;
  /** File name */
  fileName: string;
};
export type GcsStorageControllerActivateErrorModeApiResponse =
  /** status 200 Error mode activated */ ErrorModeStateDto;
export type GcsStorageControllerActivateErrorModeApiArg = {
  activateErrorModeDto: ActivateErrorModeDto;
};
export type GcsStorageControllerDeactivateErrorModeApiResponse =
  /** status 200 Error mode deactivated */ ErrorModeStateDto;
export type GcsStorageControllerDeactivateErrorModeApiArg = void;
export type YoutubeSearchControllerSearchApiResponse =
  /** status 200 Search results returned successfully */ YoutubeSearchResponseDto;
export type YoutubeSearchControllerSearchApiArg = {
  /** Search query string */
  q: string;
  /** Maximum number of results */
  maxResults?: string;
};
export type YoutubeSearchControllerActivateErrorModeApiResponse =
  /** status 200 Error mode activated successfully */ YoutubeErrorModeStateDto;
export type YoutubeSearchControllerActivateErrorModeApiArg = {
  youtubeActivateErrorModeDto: YoutubeActivateErrorModeDto;
};
export type YoutubeSearchControllerDeactivateErrorModeApiResponse =
  /** status 200 Error mode deactivated successfully */ YoutubeErrorModeStateDto;
export type YoutubeSearchControllerDeactivateErrorModeApiArg = void;
export type LeadConversionControllerConvertApiResponse = unknown;
export type LeadConversionControllerConvertApiArg = {
  id: number;
  convertLeadRequestDto: ConvertLeadRequestDto;
};
export type DashboardControllerSnapshotApiResponse =
  /** status 200  */ DashboardSnapshotDto;
export type DashboardControllerSnapshotApiArg = void;
export type ConfigurableLookupsControllerFindAllApiResponse =
  /** status 200  */ ConfigurableLookupDto[];
export type ConfigurableLookupsControllerFindAllApiArg = {
  listKey: string;
  includeInactive: string;
};
export type ConfigurableLookupsControllerCreateApiResponse =
  /** status 201  */ ConfigurableLookupDto;
export type ConfigurableLookupsControllerCreateApiArg = {
  createConfigurableLookupDto: CreateConfigurableLookupDto;
};
export type ConfigurableLookupsControllerFindOneApiResponse =
  /** status 200  */ ConfigurableLookupDto;
export type ConfigurableLookupsControllerFindOneApiArg = {
  id: number;
};
export type ConfigurableLookupsControllerUpdateApiResponse =
  /** status 200  */ ConfigurableLookupDto;
export type ConfigurableLookupsControllerUpdateApiArg = {
  id: number;
  updateConfigurableLookupDto: UpdateConfigurableLookupDto;
};
export type ConfigurableLookupsControllerDeleteApiResponse = unknown;
export type ConfigurableLookupsControllerDeleteApiArg = {
  id: number;
};
export type ActivityLogControllerFindAllApiResponse =
  /** status 200  */ ActivityLogEntryDto[];
export type ActivityLogControllerFindAllApiArg = {
  relatedType: string;
  relatedId: string;
  scope: string;
};
export type ActivityLogControllerCreateApiResponse =
  /** status 201  */ ActivityLogEntryDto;
export type ActivityLogControllerCreateApiArg = {
  createActivityLogEntryDto: CreateActivityLogEntryDto;
};
export type ActivityLogControllerFindOneApiResponse =
  /** status 200  */ ActivityLogEntryDto;
export type ActivityLogControllerFindOneApiArg = {
  id: number;
};
export type ActivityLogControllerUpdateApiResponse =
  /** status 200  */ ActivityLogEntryDto;
export type ActivityLogControllerUpdateApiArg = {
  id: number;
  updateActivityLogEntryDto: UpdateActivityLogEntryDto;
};
export type ActivityLogControllerDeleteApiResponse = unknown;
export type ActivityLogControllerDeleteApiArg = {
  id: number;
};
export type ActivityLogControllerCompleteApiResponse =
  /** status 200  */ ActivityLogEntryDto;
export type ActivityLogControllerCompleteApiArg = {
  id: number;
  completeActivityLogEntryDto: CompleteActivityLogEntryDto;
};
export type CompaniesControllerFindAllApiResponse =
  /** status 200  */ CompanyDto[];
export type CompaniesControllerFindAllApiArg = {
  ownerId: string;
  status: string;
  search: string;
  includeArchived: string;
};
export type CompaniesControllerCreateApiResponse =
  /** status 201  */ CompanyDto;
export type CompaniesControllerCreateApiArg = {
  createCompanyDto: CreateCompanyDto;
};
export type CompaniesControllerFindOneApiResponse =
  /** status 200  */ CompanyDto;
export type CompaniesControllerFindOneApiArg = {
  id: number;
};
export type CompaniesControllerUpdateApiResponse =
  /** status 200  */ CompanyDto;
export type CompaniesControllerUpdateApiArg = {
  id: number;
  updateCompanyDto: UpdateCompanyDto;
};
export type CompaniesControllerArchiveApiResponse =
  /** status 200  */ CompanyDto;
export type CompaniesControllerArchiveApiArg = {
  id: number;
};
export type CompaniesControllerRestoreApiResponse =
  /** status 200  */ CompanyDto;
export type CompaniesControllerRestoreApiArg = {
  id: number;
};
export type ContactsControllerFindAllApiResponse =
  /** status 200  */ ContactDto[];
export type ContactsControllerFindAllApiArg = {
  ownerId: string;
  companyId: string;
  status: string;
  search: string;
  includeArchived: string;
};
export type ContactsControllerCreateApiResponse = /** status 201  */ ContactDto;
export type ContactsControllerCreateApiArg = {
  createContactDto: CreateContactDto;
};
export type ContactsControllerFindOneApiResponse =
  /** status 200  */ ContactDto;
export type ContactsControllerFindOneApiArg = {
  id: number;
};
export type ContactsControllerUpdateApiResponse = /** status 200  */ ContactDto;
export type ContactsControllerUpdateApiArg = {
  id: number;
  updateContactDto: UpdateContactDto;
};
export type ContactsControllerArchiveApiResponse =
  /** status 200  */ ContactDto;
export type ContactsControllerArchiveApiArg = {
  id: number;
};
export type ContactsControllerRestoreApiResponse =
  /** status 200  */ ContactDto;
export type ContactsControllerRestoreApiArg = {
  id: number;
};
export type LeadsControllerFindAllApiResponse = /** status 200  */ LeadDto[];
export type LeadsControllerFindAllApiArg = {
  ownerId: string;
  status: string;
  search: string;
};
export type LeadsControllerCreateApiResponse = /** status 201  */ LeadDto;
export type LeadsControllerCreateApiArg = {
  createLeadDto: CreateLeadDto;
};
export type LeadsControllerFindOneApiResponse = /** status 200  */ LeadDto;
export type LeadsControllerFindOneApiArg = {
  id: number;
};
export type LeadsControllerUpdateApiResponse = /** status 200  */ LeadDto;
export type LeadsControllerUpdateApiArg = {
  id: number;
  updateLeadDto: UpdateLeadDto;
};
export type LeadsControllerDeleteApiResponse = unknown;
export type LeadsControllerDeleteApiArg = {
  id: number;
};
export type OpportunitiesControllerFindAllApiResponse =
  /** status 200  */ OpportunityDto[];
export type OpportunitiesControllerFindAllApiArg = {
  ownerId: string;
  companyId: string;
  stage: string;
  search: string;
  openOnly: string;
};
export type OpportunitiesControllerCreateApiResponse =
  /** status 201  */ OpportunityDto;
export type OpportunitiesControllerCreateApiArg = {
  createOpportunityDto: CreateOpportunityDto;
};
export type OpportunitiesControllerPipelineSummaryApiResponse = unknown;
export type OpportunitiesControllerPipelineSummaryApiArg = {
  ownerId: string;
};
export type OpportunitiesControllerFindOneApiResponse =
  /** status 200  */ OpportunityDto;
export type OpportunitiesControllerFindOneApiArg = {
  id: number;
};
export type OpportunitiesControllerUpdateApiResponse =
  /** status 200  */ OpportunityDto;
export type OpportunitiesControllerUpdateApiArg = {
  id: number;
  updateOpportunityDto: UpdateOpportunityDto;
};
export type OpportunitiesControllerCloseApiResponse =
  /** status 200  */ OpportunityDto;
export type OpportunitiesControllerCloseApiArg = {
  id: number;
  closeOpportunityDto: CloseOpportunityDto;
};
export type TwinControllerGetStatusApiResponse =
  /** status 200 Twin status retrieved successfully */ TwinStatusDto;
export type TwinControllerGetStatusApiArg = void;
export type TwinControllerStartApiResponse =
  /** status 200 Twin environment started successfully */ TwinStartResponseDto;
export type TwinControllerStartApiArg = void;
export type TwinControllerStopApiResponse =
  /** status 200 Twin environment stopped successfully */ TwinStopResponseDto;
export type TwinControllerStopApiArg = void;
export type TwinControllerGetGmailEmailsApiResponse =
  /** status 200 Intercepted emails retrieved successfully */ GmailTwinCapturedEmailDto[];
export type TwinControllerGetGmailEmailsApiArg = void;
export type TwinControllerResetGmailApiResponse =
  /** status 200 Gmail mailbox reset successfully */ GmailTwinResetResponseDto;
export type TwinControllerResetGmailApiArg = void;
export type TwinControllerSetGmailErrorModeApiResponse =
  /** status 200 Gmail twin error mode configured successfully */ GmailTwinErrorModeResponseDto;
export type TwinControllerSetGmailErrorModeApiArg = {
  setGmailErrorModeDto: SetGmailErrorModeDto;
};
export type YouTubeTwinControllerGetStatusApiResponse =
  /** status 200 YouTube twin status retrieved successfully */ YouTubeTwinStatusDto;
export type YouTubeTwinControllerGetStatusApiArg = void;
export type YouTubeTwinControllerStartApiResponse =
  /** status 200 YouTube twin started successfully */ YouTubeTwinStartResponseDto;
export type YouTubeTwinControllerStartApiArg = void;
export type YouTubeTwinControllerStopApiResponse =
  /** status 200 YouTube twin stopped successfully */ YouTubeTwinStopResponseDto;
export type YouTubeTwinControllerStopApiArg = void;
export type YouTubeTwinControllerResetApiResponse = unknown;
export type YouTubeTwinControllerResetApiArg = void;
export type GoogleAuthEmulateControllerGetStatusApiResponse =
  /** status 200  */ GoogleEmulatorStatusDto;
export type GoogleAuthEmulateControllerGetStatusApiArg = void;
export type GoogleAuthEmulateControllerStartApiResponse = unknown;
export type GoogleAuthEmulateControllerStartApiArg = void;
export type GoogleAuthEmulateControllerStopApiResponse = unknown;
export type GoogleAuthEmulateControllerStopApiArg = void;
export type GoogleAuthEmulateControllerResetApiResponse = unknown;
export type GoogleAuthEmulateControllerResetApiArg = void;
export type GoogleAuthEmulateControllerGetLoginUrlApiResponse = unknown;
export type GoogleAuthEmulateControllerGetLoginUrlApiArg = void;
export type GoogleAuthEmulateControllerLoginApiResponse = unknown;
export type GoogleAuthEmulateControllerLoginApiArg = void;
export type GoogleAuthEmulateControllerCallbackApiResponse = unknown;
export type GoogleAuthEmulateControllerCallbackApiArg = void;
export type GoogleAuthEmulateControllerGetLastResultApiResponse =
  /** status 200  */ GoogleOAuthResultDto;
export type GoogleAuthEmulateControllerGetLastResultApiArg = void;
export type GoogleAuthEmulateControllerGetLogsApiResponse =
  /** status 200  */ ApiLogEntryDto[];
export type GoogleAuthEmulateControllerGetLogsApiArg = void;
export type GoogleAuthEmulateControllerLogoutApiResponse = unknown;
export type GoogleAuthEmulateControllerLogoutApiArg = void;
export type LoginResponseDto = {
  /** JWT access token */
  access_token: string;
};
export type LoginDto = {
  /** User email address */
  email: string;
  /** User password */
  password: string;
};
export type ProfileResponseDto = {
  /** User ID */
  id: number;
  /** User first name */
  firstName: string | null;
  /** User last name */
  lastName: string | null;
  /** User email address */
  email: string;
  /** Primary role name */
  role: string | null;
  /** Granted permissions */
  permissions: string[];
};
export type SendEmailResponseDto = {
  /** Whether the email was sent successfully */
  success: boolean;
  /** Gmail message ID if successful */
  messageId?: string;
  /** Error message if failed */
  error?: string;
};
export type SendEmailDto = {
  /** Recipient email address */
  to: string;
  /** Email subject line */
  subject: string;
  /** Email body content */
  body: string;
};
export type InviteUserDto = {
  /** Email address of the user to invite */
  email: string;
  /** Role name to assign to the invited user */
  role?: string;
};
export type AcceptInvitationDto = {
  /** Invitation token from the invite link */
  token: string;
  /** Password for the new account */
  password: string;
  /** First name of the user */
  firstName?: string;
  /** Last name of the user */
  lastName?: string;
};
export type CreateRoleDto = {
  /** Unique role name */
  name: string;
  /** Role description */
  description?: string;
};
export type UpdateRoleDto = {
  /** New role name */
  name?: string;
  /** New description */
  description?: string;
};
export type SetRolePermissionsDto = {
  /** Array of permission IDs to assign */
  permissionIds: number[];
};
export type CreatePermissionDto = {
  /** Resource name */
  resource: string;
  /** Action name */
  action: string;
  /** Permission description */
  description?: string;
};
export type UpdateUserRolesDto = {
  /** Array of role IDs to assign (replaces all existing roles) */
  roleIds: number[];
};
export type AssignUserRoleDto = {
  /** Role ID to assign */
  roleId: number;
};
export type GcpProjectSummaryDto = {
  /** Full resource name (e.g. projects/123) */
  name: string;
  /** Project ID */
  projectId: string;
  /** Display name */
  displayName?: string;
  /** Project lifecycle state (e.g. ACTIVE, DELETE_REQUESTED) */
  state?: object;
};
export type CreateProjectResponseDto = {
  /** Full resource name (e.g. projects/123) */
  name: string;
  /** Project ID */
  projectId: string;
  /** Display name */
  displayName?: string;
  /** Project lifecycle state */
  state?: object;
};
export type CreateProjectDto = {
  /** Project ID (must be unique, lowercase letters, numbers, and hyphens) */
  projectId: string;
  /** Display name for the project */
  displayName?: string;
  /** Parent resource: folders/{folder_id} or organizations/{org_id} */
  parent: string;
};
export type FileMetadataDto = {
  /** File name */
  name: string;
  /** Bucket name */
  bucket: string;
  /** File size in bytes */
  size: number;
  /** Content type */
  contentType: string;
  /** Last updated timestamp */
  updated: string;
};
export type UploadFileDto = {
  /** Bucket name */
  bucket: string;
  /** File name */
  fileName: string;
  /** File content as base64 string */
  content: string;
  /** Optional content type */
  contentType?: string;
};
export type ListFilesResponseDto = {
  files: FileMetadataDto[];
};
export type GetDownloadUrlResponseDto = {
  /** Download URL */
  url: string;
  /** URL expiration timestamp */
  expiresAt: string;
};
export type GcsErrorModeType =
  | "bucket-not-found"
  | "quota-exceeded"
  | "permission-denied"
  | "intermittent-failure";
export type ErrorModeStateDto = {
  /** Whether an error mode is currently active */
  active: boolean;
  /** The active error mode type */
  type?: GcsErrorModeType;
  /** Human-readable description of what the error mode does */
  description?: string;
};
export type ActivateErrorModeDto = {
  /** The error mode to activate */
  type: GcsErrorModeType;
  /** Bucket name for bucket-not-found mode. Required when type is bucket-not-found. */
  bucketName?: string;
  /** Fail every Nth request for intermittent-failure mode. Defaults to 2. */
  failEveryN?: number;
};
export type YoutubePageInfoDto = {
  /** Total results */
  totalResults: number;
  /** Results per page */
  resultsPerPage: number;
};
export type YoutubeVideoIdDto = {
  /** Resource kind */
  kind: string;
  /** Unique video ID */
  videoId: string;
};
export type YoutubeThumbnailDetailsDto = {
  /** Thumbnail URL */
  url: string;
  /** Thumbnail width */
  width: number;
  /** Thumbnail height */
  height: number;
};
export type YoutubeThumbnailsDto = {
  default: YoutubeThumbnailDetailsDto;
  medium: YoutubeThumbnailDetailsDto;
  high: YoutubeThumbnailDetailsDto;
};
export type YoutubeSearchSnippetDto = {
  /** Publish time */
  publishedAt: string;
  /** Channel ID */
  channelId: string;
  /** Video title */
  title: string;
  /** Video description */
  description: string;
  thumbnails: YoutubeThumbnailsDto;
  /** Channel Title */
  channelTitle: string;
  /** Live broadcast content status */
  liveBroadcastContent: string;
};
export type YoutubeSearchResultItemDto = {
  /** Result item kind */
  kind: string;
  /** ETag of the item */
  etag: string;
  id: YoutubeVideoIdDto;
  snippet: YoutubeSearchSnippetDto;
};
export type YoutubeSearchResponseDto = {
  /** Search list response kind */
  kind: string;
  /** ETag */
  etag: string;
  /** Region code */
  regionCode: string;
  pageInfo: YoutubePageInfoDto;
  items: YoutubeSearchResultItemDto[];
};
export type YoutubeErrorModeType =
  | "daily-limit-exceeded"
  | "invalid-api-key"
  | "empty-results"
  | "player-error-2"
  | "player-error-5"
  | "player-error-100"
  | "player-error-101"
  | "player-error-150";
export type YoutubeErrorModeStateDto = {
  /** Whether an error mode is currently active */
  active: boolean;
  /** The active error mode type */
  type?: YoutubeErrorModeType;
  /** Human-readable description of what the error mode does */
  description?: string;
};
export type YoutubeActivateErrorModeDto = {
  /** The YouTube error mode to activate */
  type: YoutubeErrorModeType;
};
export type ConvertLeadRequestDto = {
  contactId?: number;
  companyId?: number;
  createOpportunity?: boolean;
  opportunityTitle?: string;
  opportunityEstimatedValue?: number;
};
export type StageSummaryDto = {
  stage: string;
  count: number;
  totalValue: number;
  weightedValue: number;
};
export type DashboardSnapshotDto = {
  pipeline: StageSummaryDto[];
  tasksOpen: number;
  tasksOverdue: number;
};
export type ConfigurableLookupDto = {
  id: number;
  listKey: string;
  value: string;
  label: string;
  sortOrder: number;
  isSystem: boolean;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
};
export type CreateConfigurableLookupDto = {
  /** snake_case list key */
  listKey: string;
  /** snake_case canonical value */
  value: string;
  label: string;
  sortOrder?: number;
  isActive?: boolean;
};
export type UpdateConfigurableLookupDto = {
  listKey?: string;
  value?: string;
  label?: string;
  sortOrder?: number;
  isActive?: boolean;
};
export type ActivityLogEntryDto = {
  id: number;
  /** Polymorphic identifier for the related record kind. Validated against the allowed-types list registered via DataAccessActivityLogModule.forRoot(). */
  relatedType: string;
  relatedId: number;
  /** Activity type. Validated against the allowed-types list registered via DataAccessActivityLogModule.forRoot(). */
  type: string;
  subject: string;
  description?: object | null;
  dueAt?: string | null;
  completedAt?: string | null;
  ownerId: number;
  createdAt: string;
  updatedAt: string;
};
export type CreateActivityLogEntryDto = {
  relatedType: string;
  relatedId: number;
  type: string;
  subject: string;
  description?: string;
  dueAt?: string;
};
export type UpdateActivityLogEntryDto = {
  subject?: string;
  description?: object;
  dueAt?: string;
};
export type CompleteActivityLogEntryDto = {
  outcomeNotes?: string;
};
export type CompanyDto = {
  id: number;
  name: string;
  website?: object | null;
  primaryPhone?: object | null;
  industry?: object | null;
  status: string;
  location?: object | null;
  companySize?: object | null;
  revenueRange?: object | null;
  notesSummary?: object | null;
  ownerId: number;
  isArchived: boolean;
  createdAt: string;
  updatedAt: string;
};
export type CreateCompanyDto = {
  name: string;
  website?: string;
  primaryPhone?: string;
  industry?: string;
  status?: string;
  location?: string;
  companySize?: string;
  revenueRange?: string;
  notesSummary?: string;
  /** Owner user id. Defaults to the authenticated user. */
  ownerId?: number;
};
export type UpdateCompanyDto = {
  name?: string;
  website?: object;
  primaryPhone?: object;
  industry?: object;
  status?: string;
  location?: object;
  companySize?: object;
  revenueRange?: object;
  notesSummary?: object;
  ownerId?: number;
};
export type ContactDto = {
  id: number;
  firstName: string;
  lastName: string;
  email?: object | null;
  phone?: object | null;
  secondaryPhone?: object | null;
  secondaryEmail?: object | null;
  jobTitle?: object | null;
  companyId?: object | null;
  leadSource?: object | null;
  tags?: object | null;
  mailingAddress?: object | null;
  notesSummary?: object | null;
  status: string;
  ownerId: number;
  isArchived: boolean;
  createdAt: string;
  updatedAt: string;
};
export type CreateContactDto = {
  firstName: string;
  lastName: string;
  email?: string;
  phone?: string;
  secondaryPhone?: string;
  secondaryEmail?: string;
  jobTitle?: string;
  companyId?: number;
  leadSource?: string;
  tags?: string;
  mailingAddress?: string;
  notesSummary?: string;
  status?: string;
  /** Owner user id. Defaults to the authenticated user. */
  ownerId?: number;
};
export type UpdateContactDto = {
  firstName?: string;
  lastName?: string;
  email?: object;
  phone?: object;
  secondaryPhone?: object;
  secondaryEmail?: object;
  jobTitle?: object;
  companyId?: object;
  leadSource?: object;
  tags?: object;
  mailingAddress?: object;
  notesSummary?: object;
  status?: string;
  ownerId?: number;
};
export type LeadDto = {
  id: number;
  name: string;
  companyName?: object | null;
  email?: object | null;
  phone?: object | null;
  source?: object | null;
  status: "new" | "contacted" | "qualified" | "unqualified";
  notes?: object | null;
  contactId?: object | null;
  companyId?: object | null;
  convertedAt?: string | null;
  convertedToContactId?: object | null;
  convertedToCompanyId?: object | null;
  ownerId: number;
  createdAt: string;
  updatedAt: string;
};
export type CreateLeadDto = {
  name: string;
  companyName?: string;
  email?: string;
  phone?: string;
  source?: string;
  status?: "new" | "contacted" | "qualified" | "unqualified";
  notes?: string;
  ownerId?: number;
};
export type UpdateLeadDto = {
  name?: string;
  companyName?: object;
  email?: object;
  phone?: object;
  source?: object;
  status?: "new" | "contacted" | "qualified" | "unqualified";
  notes?: object;
  ownerId?: number;
};
export type OpportunityDto = {
  id: number;
  title: string;
  companyId: number;
  primaryContactId?: object | null;
  stage: "new" | "discovery" | "proposal" | "negotiation" | "won" | "lost";
  estimatedValue?: object | null;
  probability?: object | null;
  expectedCloseDate?: string | null;
  closedAt?: string | null;
  lossReason?: object | null;
  notes?: object | null;
  ownerId: number;
  createdAt: string;
  updatedAt: string;
};
export type CreateOpportunityDto = {
  title: string;
  companyId: number;
  primaryContactId?: number;
  stage?: "new" | "discovery" | "proposal" | "negotiation" | "won" | "lost";
  estimatedValue?: number;
  probability?: number;
  expectedCloseDate?: string;
  notes?: string;
  ownerId?: number;
};
export type UpdateOpportunityDto = {
  title?: string;
  companyId?: number;
  primaryContactId?: object;
  stage?: "new" | "discovery" | "proposal" | "negotiation" | "won" | "lost";
  estimatedValue?: object;
  probability?: object;
  expectedCloseDate?: string;
  notes?: object;
  ownerId?: number;
};
export type CloseOpportunityDto = {
  outcome: "won" | "lost";
  lossReason?: string;
};
export type GmailTwinStatusDto = {
  /** Whether the Gmail mock server is currently running */
  running: boolean;
  /** Whether the Gmail mock server is healthy */
  healthy: boolean;
  /** The port the Gmail mock server is listening on */
  port: number;
  /** The URL of the Gmail mock server */
  url?: string;
};
export type TwinStatusDto = {
  /** Whether the twin emulator is currently running */
  running: boolean;
  /** Whether the twin emulator is healthy */
  healthy: boolean;
  /** The port the twin emulator is listening on */
  port: number;
  /** The URL of the twin emulator */
  url?: string;
  /** Whether GCS storage emulator is online */
  gcsOnline: boolean;
  /** Current error simulation mode state */
  errorMode: ErrorModeStateDto;
  /** Status of the Gmail twin emulator */
  gmail?: GmailTwinStatusDto;
  /** Whether the global fetch/HTTP request interceptor is active */
  interceptorActive: boolean;
  /** Whether real Gmail credentials are fully configured in the environment */
  realGmailConfigured: boolean;
};
export type TwinStartResponseDto = {
  success: boolean;
  message: string;
  url?: string;
};
export type TwinStopResponseDto = {
  success: boolean;
  message: string;
};
export type GmailTwinCapturedEmailDto = {
  /** The unique message identifier */
  id: string;
  /** The thread identifier of the message */
  threadId: string;
  /** List of recipient email addresses */
  to: string[];
  /** Sender email address */
  from: string;
  /** Email subject line */
  subject: string;
  /** Plaintext message content */
  text?: string;
  /** HTML message content */
  html?: string;
  /** ISO timestamp when the email was captured */
  timestamp: string;
  /** The raw base64url encoded email package */
  raw: string;
};
export type GmailTwinResetResponseDto = {
  success: boolean;
  message: string;
};
export type GmailTwinErrorModeResponseDto = {
  success: boolean;
  message: string;
};
export type SetGmailErrorModeDto = {
  /** The simulated error mode to activate */
  mode: "none" | "rate-limit" | "auth-error" | "bad-request";
};
export type YouTubeTwinStatusDto = {
  /** Whether the YouTube twin emulator is currently running */
  running: boolean;
  /** Whether the YouTube twin emulator is healthy */
  healthy: boolean;
  /** The port the YouTube twin emulator is listening on */
  port: number;
  /** The URL of the YouTube twin emulator */
  url?: string;
  /** Current YouTube error simulation mode state */
  errorMode: YoutubeErrorModeStateDto;
};
export type YouTubeTwinStartResponseDto = {
  success: boolean;
  message: string;
  url?: string;
};
export type YouTubeTwinStopResponseDto = {
  success: boolean;
  message: string;
};
export type GoogleEmulatorStatusDto = {
  /** Indicates whether the Google emulator server is running */
  running: boolean;
  /** Indicates whether the Google emulator server is healthy */
  healthy: boolean;
  /** Port on which the emulator is listening */
  port: number;
  /** Base URL of the running emulator */
  url?: string;
};
export type GoogleOAuthTokensDto = {
  /** Google OAuth Access Token */
  access_token: string;
  /** Google OIDC ID Token */
  id_token: string;
  /** Google OAuth Refresh Token */
  refresh_token?: string;
  /** Token expiration duration in seconds */
  expires_in: number;
  /** Token type */
  token_type: string;
  /** Granted scopes */
  scope: string;
};
export type GoogleUserProfileDto = {
  /** Subject / User ID */
  sub: string;
  /** User email address */
  email: string;
  /** Full name of the user */
  name: string;
  /** Profile picture URL */
  picture: string;
  /** Whether the email address has been verified */
  email_verified: boolean;
  /** Hosted domain if applicable */
  hd?: string;
};
export type ApiLogEntryDto = {
  /** Unique log ID */
  id: string;
  /** ISO Timestamp */
  timestamp: string;
  /** HTTP Method */
  method: string;
  /** Request URL */
  url: string;
  /** HTTP Response Status Code */
  statusCode: number;
  /** Request headers object */
  requestHeaders: object;
  /** Request body */
  requestBody?: string;
  /** Response headers object */
  responseHeaders: object;
  /** Response body payload */
  responseBody: string;
  /** Latency in milliseconds */
  latencyMs: number;
};
export type GoogleOAuthResultDto = {
  tokens: GoogleOAuthTokensDto;
  userProfile: GoogleUserProfileDto;
  apiLogs: ApiLogEntryDto[];
};
export const {
  useAuthControllerLoginMutation,
  useAuthControllerGetProfileQuery,
  useEmailControllerSendEmailMutation,
  useInvitationsControllerFindAllQuery,
  useInvitationsControllerInviteMutation,
  useInvitationsControllerValidateQuery,
  useInvitationsControllerAcceptMutation,
  useInvitationsControllerCancelMutation,
  useUsersControllerFindAllQuery,
  useUsersControllerFindOneQuery,
  useUsersControllerDeleteMutation,
  useRolesControllerFindAllQuery,
  useRolesControllerCreateMutation,
  useRolesControllerFindOneQuery,
  useRolesControllerUpdateMutation,
  useRolesControllerDeleteMutation,
  useRolesControllerGetPermissionsQuery,
  useRolesControllerSetPermissionsMutation,
  usePermissionsControllerFindAllQuery,
  usePermissionsControllerCreateMutation,
  usePermissionsControllerFindOneQuery,
  usePermissionsControllerDeleteMutation,
  useUserRolesControllerFindByUserQuery,
  useUserRolesControllerSetRolesMutation,
  useUserRolesControllerAssignRoleMutation,
  useUserRolesControllerRemoveRoleMutation,
  useGcpProjectsControllerListProjectsQuery,
  useGcpProjectsControllerCreateProjectMutation,
  useGcsStorageControllerUploadFileMutation,
  useGcsStorageControllerListFilesQuery,
  useGcsStorageControllerGenerateDownloadUrlQuery,
  useGcsStorageControllerDownloadFileQuery,
  useGcsStorageControllerDeleteFileMutation,
  useGcsStorageControllerActivateErrorModeMutation,
  useGcsStorageControllerDeactivateErrorModeMutation,
  useYoutubeSearchControllerSearchQuery,
  useYoutubeSearchControllerActivateErrorModeMutation,
  useYoutubeSearchControllerDeactivateErrorModeMutation,
  useLeadConversionControllerConvertMutation,
  useDashboardControllerSnapshotQuery,
  useConfigurableLookupsControllerFindAllQuery,
  useConfigurableLookupsControllerCreateMutation,
  useConfigurableLookupsControllerFindOneQuery,
  useConfigurableLookupsControllerUpdateMutation,
  useConfigurableLookupsControllerDeleteMutation,
  useActivityLogControllerFindAllQuery,
  useActivityLogControllerCreateMutation,
  useActivityLogControllerFindOneQuery,
  useActivityLogControllerUpdateMutation,
  useActivityLogControllerDeleteMutation,
  useActivityLogControllerCompleteMutation,
  useCompaniesControllerFindAllQuery,
  useCompaniesControllerCreateMutation,
  useCompaniesControllerFindOneQuery,
  useCompaniesControllerUpdateMutation,
  useCompaniesControllerArchiveMutation,
  useCompaniesControllerRestoreMutation,
  useContactsControllerFindAllQuery,
  useContactsControllerCreateMutation,
  useContactsControllerFindOneQuery,
  useContactsControllerUpdateMutation,
  useContactsControllerArchiveMutation,
  useContactsControllerRestoreMutation,
  useLeadsControllerFindAllQuery,
  useLeadsControllerCreateMutation,
  useLeadsControllerFindOneQuery,
  useLeadsControllerUpdateMutation,
  useLeadsControllerDeleteMutation,
  useOpportunitiesControllerFindAllQuery,
  useOpportunitiesControllerCreateMutation,
  useOpportunitiesControllerPipelineSummaryQuery,
  useOpportunitiesControllerFindOneQuery,
  useOpportunitiesControllerUpdateMutation,
  useOpportunitiesControllerCloseMutation,
  useTwinControllerGetStatusQuery,
  useTwinControllerStartMutation,
  useTwinControllerStopMutation,
  useTwinControllerGetGmailEmailsQuery,
  useTwinControllerResetGmailMutation,
  useTwinControllerSetGmailErrorModeMutation,
  useYouTubeTwinControllerGetStatusQuery,
  useYouTubeTwinControllerStartMutation,
  useYouTubeTwinControllerStopMutation,
  useYouTubeTwinControllerResetMutation,
  useGoogleAuthEmulateControllerGetStatusQuery,
  useGoogleAuthEmulateControllerStartMutation,
  useGoogleAuthEmulateControllerStopMutation,
  useGoogleAuthEmulateControllerResetMutation,
  useGoogleAuthEmulateControllerGetLoginUrlQuery,
  useGoogleAuthEmulateControllerLoginQuery,
  useGoogleAuthEmulateControllerCallbackQuery,
  useGoogleAuthEmulateControllerGetLastResultQuery,
  useGoogleAuthEmulateControllerGetLogsQuery,
  useGoogleAuthEmulateControllerLogoutMutation,
} = injectedRtkApi;
