// AUTO-GENERATED FILE @generated by @open-kingdom/plugin-openapi
// Run "nx run @open-kingdom/plugin-openapi:generate-client-all" to regenerate.
export * from './demo-scaffold-backend/api';
export * as demoScaffoldBackend from './demo-scaffold-backend/api';
