import { loggerReducer, addLog, clearLogs } from './logger.slice';
import { LoggerState, LogEntry } from './logger.types';

describe('Logger Slice', () => {
  const initialState: LoggerState = {
    logs: [],
  };

  describe('reducer', () => {
    it('should return initial state when called with undefined state', () => {
      const result = loggerReducer(undefined, { type: 'unknown' });
      expect(result).toEqual(initialState);
    });

    it('should handle addLog action', () => {
      const logPayload = {
        message: 'Test message',
        level: 'info' as const,
      };

      // Mock Date.now to get predictable values
      const mockTimestamp = 1234567890;
      jest.spyOn(Date, 'now').mockReturnValue(mockTimestamp);

      const action = addLog(logPayload);
      const result = loggerReducer(initialState, action);

      expect(result.logs).toHaveLength(1);
      expect(result.logs[0]).toEqual({
        id: mockTimestamp.toString(),
        timestamp: mockTimestamp,
        message: 'Test message',
        level: 'info',
      });

      jest.restoreAllMocks();
    });

    it('should add multiple logs maintaining order', () => {
      const firstLog = {
        message: 'First message',
        level: 'info' as const,
      };
      
      const secondLog = {
        message: 'Second message',
        level: 'warn' as const,
      };

      // Create actions manually and then dispatch to reducer
      let state = loggerReducer(initialState, addLog(firstLog));
      state = loggerReducer(state, addLog(secondLog));

      expect(state.logs).toHaveLength(2);
      expect(state.logs[0].message).toBe('First message');
      expect(state.logs[1].message).toBe('Second message');
      // Don't test specific timestamps since they're generated by Date.now()
      // but verify they exist and are numbers
      expect(typeof state.logs[0].timestamp).toBe('number');
      expect(typeof state.logs[1].timestamp).toBe('number');
      expect(state.logs[0].id).toBeDefined();
      expect(state.logs[1].id).toBeDefined();
    });

    it('should handle clearLogs action', () => {
      const stateWithLogs: LoggerState = {
        logs: [
          {
            id: '1',
            message: 'Test message',
            level: 'info',
            timestamp: Date.now(),
          },
        ],
      };

      const result = loggerReducer(stateWithLogs, clearLogs());
      expect(result.logs).toEqual([]);
    });

    it('should handle all log levels', () => {
      const mockTimestamp = 1234567890;
      jest.spyOn(Date, 'now').mockReturnValue(mockTimestamp);

      const levels = ['info', 'warn', 'error'] as const;
      let state = initialState;

      levels.forEach((level, index) => {
        const logPayload = {
          message: `${level} message`,
          level,
        };
        state = loggerReducer(state, addLog(logPayload));
      });

      expect(state.logs).toHaveLength(3);
      levels.forEach((level, index) => {
        expect(state.logs[index].level).toBe(level);
        expect(state.logs[index].message).toBe(`${level} message`);
      });

      jest.restoreAllMocks();
    });
  });

  describe('actions', () => {
    it('should create addLog action with correct type', () => {
      const payload = { message: 'test', level: 'info' as const };
      const action = addLog(payload);
      
      expect(action.type).toBe('logger/addLog');
      expect(action.payload).toEqual(payload);
    });

    it('should create clearLogs action with correct type', () => {
      const action = clearLogs();
      expect(action.type).toBe('logger/clearLogs');
      expect(action.payload).toBeUndefined();
    });
  });
}); 